web: uvicorn app.main:app --host 0.0.0.0 --port $PORT
worker: celery -A app.core.celery_app:celery_app worker --loglevel=info --pool=threads --concurrency=4 -Q media-intelligence
beat: celery -A app.core.celery_app:celery_app beat --loglevel=info
