PUBLISHER_COUNTRY_BY_DOMAIN = {
    "bbc.com": {"country_code": "GB", "country_name": "United Kingdom"},
    "thehindu.com": {"country_code": "IN", "country_name": "India"},
    "nytimes.com": {"country_code": "US", "country_name": "United States"},
    "abc.net.au": {"country_code": "AU", "country_name": "Australia"},
    "reuters.com": {"country_code": "GB", "country_name": "United Kingdom"},
    "apnews.com": {"country_code": "US", "country_name": "United States"},
    "rte.ie": {"country_code": "IE", "country_name": "Ireland"},
    "theverge.com": {"country_code": "US", "country_name": "United States"},
    "prnewswire.com": {"country_code": "US", "country_name": "United States"},
    "qz.com": {"country_code": "US", "country_name": "United States"},
    "gizmodo.com": {"country_code": "US", "country_name": "United States"},
    "techradar.com": {"country_code": "GB", "country_name": "United Kingdom"},
    "naturalnews.com": {"country_code": "US", "country_name": "United States"},
    "247wallst.com": {"country_code": "US", "country_name": "United States"},
    "bloomberg.com": {"country_code": "US", "country_name": "United States"},
    "theguardian.com": {"country_code": "GB", "country_name": "United Kingdom"},
    "siliconangle.com": {"country_code": "US", "country_name": "United States"},
    "fortune.com": {"country_code": "US", "country_name": "United States"},
    "cbsnews.com": {"country_code": "US", "country_name": "United States"},
    "tomshardware.com": {"country_code": "US", "country_name": "United States"},
    "freerepublic.com": {"country_code": "US", "country_name": "United States"},
    "finance.yahoo.com": {"country_code": "US", "country_name": "United States"},
    "cnn.com": {"country_code": "US", "country_name": "United States"},
    "politico.com": {"country_code": "US", "country_name": "United States"},
    "aljazeera.com": {"country_code": "QA", "country_name": "Qatar"},
}

PUBLISHER_COUNTRY_BY_NAME = {
    "the hindu": {"country_code": "IN", "country_name": "India"},
    "the new york times": {"country_code": "US", "country_name": "United States"},
    "bbc news": {"country_code": "GB", "country_name": "United Kingdom"},
    "bbc": {"country_code": "GB", "country_name": "United Kingdom"},
    "qz.com": {"country_code": "US", "country_name": "United States"},
    "bloomberg.com": {"country_code": "US", "country_name": "United States"},
    "the guardian": {"country_code": "GB", "country_name": "United Kingdom"},
    "cbs news": {"country_code": "US", "country_name": "United States"},
    "cnn": {"country_code": "US", "country_name": "United States"},
    "politico": {"country_code": "US", "country_name": "United States"},
    "al jazeera": {"country_code": "QA", "country_name": "Qatar"},
    "reuters": {"country_code": "GB", "country_name": "United Kingdom"},
    "yahoo entertainment": {"country_code": "US", "country_name": "United States"},
    "finance.yahoo.com": {"country_code": "US", "country_name": "United States"},
    "fortune": {"country_code": "US", "country_name": "United States"},
}
