"""allow pending and failed report lifecycle

Revision ID: 12077fa4eced
Revises: a1b2c3d4e5f6
Create Date: 2026-09-17 00:23:39.141915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12077fa4eced'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_reports', 'filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('generated_reports', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('generated_reports', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_reports', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('generated_reports', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('generated_reports', 'filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
