"""add risk insight persistence

Revision ID: 1b8f58c47671
Revises: 28d2e7f58a58
Create Date: 2026-09-10 21:32:27.462039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8f58c47671'
down_revision: Union[str, Sequence[str], None] = '28d2e7f58a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('key_reasons', sa.JSON(), nullable=False),
    sa.Column('attention_level', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_risk_insights_article_company')
    )
    op.create_index(op.f('ix_risk_insights_article_id'), 'risk_insights', ['article_id'], unique=False)
    op.create_index(op.f('ix_risk_insights_attention_level'), 'risk_insights', ['attention_level'], unique=False)
    op.create_index(op.f('ix_risk_insights_company_id'), 'risk_insights', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_insights_risk_assessment_id'), 'risk_insights', ['risk_assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_insights_risk_assessment_id'), table_name='risk_insights')
    op.drop_index(op.f('ix_risk_insights_company_id'), table_name='risk_insights')
    op.drop_index(op.f('ix_risk_insights_attention_level'), table_name='risk_insights')
    op.drop_index(op.f('ix_risk_insights_article_id'), table_name='risk_insights')
    op.drop_table('risk_insights')
    # ### end Alembic commands ###
