"""add risk assessment persistence

Revision ID: 28d2e7f58a58
Revises: 8e68c89f79d3
Create Date: 2026-09-10 21:11:58.237945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d2e7f58a58'
down_revision: Union[str, Sequence[str], None] = '8e68c89f79d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('monitoring_topic', sa.String(length=200), nullable=True),
    sa.Column('topic_priority', sa.String(length=20), nullable=False),
    sa.Column('priority_source', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('escalation_action', sa.String(length=20), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_immediate_alert', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_id'], ['article_triages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_risk_assessments_article_company')
    )
    op.create_index(op.f('ix_risk_assessments_article_id'), 'risk_assessments', ['article_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_company_id'), 'risk_assessments', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_escalation_action'), 'risk_assessments', ['escalation_action'], unique=False)
    op.create_index(op.f('ix_risk_assessments_event_type'), 'risk_assessments', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_score'), 'risk_assessments', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_assessments_topic_priority'), 'risk_assessments', ['topic_priority'], unique=False)
    op.create_index(op.f('ix_risk_assessments_triage_id'), 'risk_assessments', ['triage_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_urgency'), 'risk_assessments', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_urgency'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_triage_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_topic_priority'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_event_type'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_escalation_action'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_company_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_article_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
