"""Add report scope fields

Revision ID: 3bf419fa38c3
Revises: 8ab5ac365549
Create Date: 2026-09-23 21:30:42.080273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf419fa38c3'
down_revision: Union[str, Sequence[str], None] = '8ab5ac365549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_reports', sa.Column('report_scope', sa.String(length=50), server_default='standard', nullable=False))
    op.add_column('generated_reports', sa.Column('scope_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_reports', 'scope_metadata')
    op.drop_column('generated_reports', 'report_scope')
    # ### end Alembic commands ###
