"""add event clustering tables

Revision ID: 47c5d55524ec
Revises: abc6936d22e7
Create Date: 2026-09-16 21:47:22.455467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c5d55524ec'
down_revision: Union[str, Sequence[str], None] = 'abc6936d22e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('representative_article_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['representative_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_clusters_company_id'), 'event_clusters', ['company_id'], unique=False)
    op.create_index(op.f('ix_event_clusters_first_published_at'), 'event_clusters', ['first_published_at'], unique=False)
    op.create_index(op.f('ix_event_clusters_last_published_at'), 'event_clusters', ['last_published_at'], unique=False)
    op.create_index(op.f('ix_event_clusters_representative_article_id'), 'event_clusters', ['representative_article_id'], unique=False)
    op.create_table('event_cluster_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['event_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_event_cluster_memberships_article_company')
    )
    op.create_index(op.f('ix_event_cluster_memberships_article_id'), 'event_cluster_memberships', ['article_id'], unique=False)
    op.create_index(op.f('ix_event_cluster_memberships_cluster_id'), 'event_cluster_memberships', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_event_cluster_memberships_company_id'), 'event_cluster_memberships', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_cluster_memberships_company_id'), table_name='event_cluster_memberships')
    op.drop_index(op.f('ix_event_cluster_memberships_cluster_id'), table_name='event_cluster_memberships')
    op.drop_index(op.f('ix_event_cluster_memberships_article_id'), table_name='event_cluster_memberships')
    op.drop_table('event_cluster_memberships')
    op.drop_index(op.f('ix_event_clusters_representative_article_id'), table_name='event_clusters')
    op.drop_index(op.f('ix_event_clusters_last_published_at'), table_name='event_clusters')
    op.drop_index(op.f('ix_event_clusters_first_published_at'), table_name='event_clusters')
    op.drop_index(op.f('ix_event_clusters_company_id'), table_name='event_clusters')
    op.drop_table('event_clusters')
    # ### end Alembic commands ###
