"""add alert persistence

Revision ID: 4fcdf143b86b
Revises: 1b8f58c47671
Create Date: 2026-09-11 16:03:14.569976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcdf143b86b'
down_revision: Union[str, Sequence[str], None] = '1b8f58c47671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('risk_insight_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('delivery_channel', sa.String(length=30), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('requires_immediate_delivery', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_insight_id'], ['risk_insights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', 'alert_type', name='uq_alerts_article_company_type')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_article_id'), 'alerts', ['article_id'], unique=False)
    op.create_index(op.f('ix_alerts_company_id'), 'alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_alerts_delivery_channel'), 'alerts', ['delivery_channel'], unique=False)
    op.create_index(op.f('ix_alerts_delivery_status'), 'alerts', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_alerts_risk_assessment_id'), 'alerts', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_alerts_risk_insight_id'), 'alerts', ['risk_insight_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_sla_due_at'), 'alerts', ['sla_due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_sla_due_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_insight_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_assessment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_delivery_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_delivery_channel'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_company_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_article_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
