"""add article business impact analysis

Revision ID: 5d6528bf133f
Revises: b125ebc8d088
Create Date: 2026-09-16 21:06:12.844201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6528bf133f'
down_revision: Union[str, Sequence[str], None] = 'b125ebc8d088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_business_impacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('primary_category', sa.String(length=30), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('impact_summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_article_business_impacts_article_company')
    )
    op.create_index(op.f('ix_article_business_impacts_article_id'), 'article_business_impacts', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_business_impacts_company_id'), 'article_business_impacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_article_business_impacts_primary_category'), 'article_business_impacts', ['primary_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_business_impacts_primary_category'), table_name='article_business_impacts')
    op.drop_index(op.f('ix_article_business_impacts_company_id'), table_name='article_business_impacts')
    op.drop_index(op.f('ix_article_business_impacts_article_id'), table_name='article_business_impacts')
    op.drop_table('article_business_impacts')
    # ### end Alembic commands ###
