"""Add IngestionRun model

Revision ID: 8883052ec047
Revises: d3a9b6f42c10
Create Date: 2026-10-01 07:20:53.518846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8883052ec047'
down_revision: Union[str, Sequence[str], None] = 'd3a9b6f42c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.Column('total_inserted', sa.Integer(), nullable=False),
    sa.Column('total_skipped', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_company_id'), 'ingestion_runs', ['company_id'], unique=False)
    op.drop_index(op.f('ix_company_locations_company_id'), table_name='company_locations')
    op.drop_table('company_locations')
    op.drop_index(op.f('ix_articles_publisher_country'), table_name='articles')
    op.drop_column('articles', 'publisher_country_resolution')
    op.drop_column('articles', 'publisher_country')
    op.drop_constraint(op.f('company_configurations_company_id_key'), 'company_configurations', type_='unique')
    op.drop_index(op.f('ix_company_configurations_company_id'), table_name='company_configurations')
    op.create_index(op.f('ix_company_configurations_company_id'), 'company_configurations', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_configurations_company_id'), table_name='company_configurations')
    op.create_index(op.f('ix_company_configurations_company_id'), 'company_configurations', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('company_configurations_company_id_key'), 'company_configurations', ['company_id'], postgresql_nulls_not_distinct=False)
    op.add_column('articles', sa.Column('publisher_country', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('publisher_country_resolution', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_articles_publisher_country'), 'articles', ['publisher_country'], unique=False)
    op.create_table('company_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_locations_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_locations_pkey'))
    )
    op.create_index(op.f('ix_company_locations_company_id'), 'company_locations', ['company_id'], unique=False)
    op.drop_index(op.f('ix_ingestion_runs_company_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
