"""report_batch_snapshot

Revision ID: 8ab5ac365549
Revises: 12077fa4eced
Create Date: 2026-09-19 19:53:22.679592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ab5ac365549'
down_revision: Union[str, Sequence[str], None] = '12077fa4eced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_reports', sa.Column('batch_id', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('generated_reports', sa.Column('time_mode', sa.String(length=20), server_default='media', nullable=False))
    op.add_column('generated_reports', sa.Column('included_article_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_constraint(op.f('uq_generated_report_period_format'), 'generated_reports', type_='unique')
    op.create_index(op.f('ix_generated_reports_batch_id'), 'generated_reports', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_reports_batch_id'), table_name='generated_reports')
    op.create_unique_constraint(op.f('uq_generated_report_period_format'), 'generated_reports', ['company_id', 'report_type', 'period_start', 'period_end', 'file_format'], postgresql_nulls_not_distinct=False)
    op.drop_column('generated_reports', 'included_article_ids')
    op.drop_column('generated_reports', 'time_mode')
    op.drop_column('generated_reports', 'snapshot_at')
    op.drop_column('generated_reports', 'batch_id')
    # ### end Alembic commands ###
