"""add article triage persistence

Revision ID: 8e68c89f79d3
Revises: e26fd6852e6b
Create Date: 2026-09-10 19:48:40.052170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e68c89f79d3'
down_revision: Union[str, Sequence[str], None] = 'e26fd6852e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_triages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('potential_impact', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_article_triages_article_company')
    )
    op.create_index(op.f('ix_article_triages_article_id'), 'article_triages', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_triages_company_id'), 'article_triages', ['company_id'], unique=False)
    op.create_index(op.f('ix_article_triages_event_type'), 'article_triages', ['event_type'], unique=False)
    op.create_index(op.f('ix_article_triages_urgency'), 'article_triages', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_triages_urgency'), table_name='article_triages')
    op.drop_index(op.f('ix_article_triages_event_type'), table_name='article_triages')
    op.drop_index(op.f('ix_article_triages_company_id'), table_name='article_triages')
    op.drop_index(op.f('ix_article_triages_article_id'), table_name='article_triages')
    op.drop_table('article_triages')
    # ### end Alembic commands ###
