"""add company intelligence context

Revision ID: 9d41fef10d8c
Revises: 92ad25bdc0f8
Create Date: 2026-09-08 22:01:44.970114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d41fef10d8c'
down_revision: Union[str, Sequence[str], None] = '92ad25bdc0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'alias', name='uq_company_aliases_company_alias')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('company_geographies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('geography', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'geography', name='uq_company_geographies_company_geography')
    )
    op.create_index(op.f('ix_company_geographies_company_id'), 'company_geographies', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_geographies_geography'), 'company_geographies', ['geography'], unique=False)
    op.create_table('company_regulators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('regulator', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'regulator', name='uq_company_regulators_company_regulator')
    )
    op.create_index(op.f('ix_company_regulators_company_id'), 'company_regulators', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_regulators_regulator'), 'company_regulators', ['regulator'], unique=False)
    op.create_table('company_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('related_company_name', sa.String(length=200), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'related_company_name', 'relationship_type', name='uq_company_relationship')
    )
    op.create_index(op.f('ix_company_relationships_company_id'), 'company_relationships', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_relationships_related_company_name'), 'company_relationships', ['related_company_name'], unique=False)
    op.create_index(op.f('ix_company_relationships_relationship_type'), 'company_relationships', ['relationship_type'], unique=False)
    op.create_table('monitoring_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'topic', name='uq_monitoring_topics_company_topic')
    )
    op.create_index(op.f('ix_monitoring_topics_company_id'), 'monitoring_topics', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitoring_topics_topic'), 'monitoring_topics', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_topics_topic'), table_name='monitoring_topics')
    op.drop_index(op.f('ix_monitoring_topics_company_id'), table_name='monitoring_topics')
    op.drop_table('monitoring_topics')
    op.drop_index(op.f('ix_company_relationships_relationship_type'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_related_company_name'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_company_id'), table_name='company_relationships')
    op.drop_table('company_relationships')
    op.drop_index(op.f('ix_company_regulators_regulator'), table_name='company_regulators')
    op.drop_index(op.f('ix_company_regulators_company_id'), table_name='company_regulators')
    op.drop_table('company_regulators')
    op.drop_index(op.f('ix_company_geographies_geography'), table_name='company_geographies')
    op.drop_index(op.f('ix_company_geographies_company_id'), table_name='company_geographies')
    op.drop_table('company_geographies')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    # ### end Alembic commands ###
