"""add article embedding fields

Revision ID: a93de9c0e29e
Revises: f20b44260fb1
Create Date: 2026-09-09 22:04:31.578279

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93de9c0e29e'
down_revision: Union[str, Sequence[str], None] = 'f20b44260fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('embedding', Vector(1536), nullable=True))
    op.add_column('articles', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('articles', sa.Column('embedding_error', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_articles_embedded_at'), 'articles', ['embedded_at'], unique=False)
    op.create_index(op.f('ix_articles_embedding_status'), 'articles', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_embedding_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_embedded_at'), table_name='articles')
    op.drop_column('articles', 'embedded_at')
    op.drop_column('articles', 'embedding_error')
    op.drop_column('articles', 'embedding_status')
    op.drop_column('articles', 'embedding_model')
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###
