"""add article embedding hnsw index

Revision ID: ab25b05d0652
Revises: a93de9c0e29e
Create Date: 2026-09-09 22:19:35.508641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab25b05d0652'
down_revision: Union[str, Sequence[str], None] = 'a93de9c0e29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_embedding_hnsw_cosine', 'articles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('embedding IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_embedding_hnsw_cosine', table_name='articles', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('embedding IS NOT NULL'))
    # ### end Alembic commands ###
