"""add article competitor mentions

Revision ID: abc6936d22e7
Revises: 5d6528bf133f
Create Date: 2026-09-16 21:23:48.487983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc6936d22e7'
down_revision: Union[str, Sequence[str], None] = '5d6528bf133f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_competitor_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_article_competitor_mentions_article_company')
    )
    op.create_index(op.f('ix_article_competitor_mentions_article_id'), 'article_competitor_mentions', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_competitor_mentions_company_id'), 'article_competitor_mentions', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_competitor_mentions_company_id'), table_name='article_competitor_mentions')
    op.drop_index(op.f('ix_article_competitor_mentions_article_id'), table_name='article_competitor_mentions')
    op.drop_table('article_competitor_mentions')
    # ### end Alembic commands ###
