"""add article sentiment analysis

Revision ID: b125ebc8d088
Revises: c5a6738cf250
Create Date: 2026-09-16 11:03:00.714234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b125ebc8d088'
down_revision: Union[str, Sequence[str], None] = 'c5a6738cf250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'company_id', name='uq_article_sentiments_article_company')
    )
    op.create_index(op.f('ix_article_sentiments_article_id'), 'article_sentiments', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_sentiments_company_id'), 'article_sentiments', ['company_id'], unique=False)
    op.create_index(op.f('ix_article_sentiments_label'), 'article_sentiments', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_sentiments_label'), table_name='article_sentiments')
    op.drop_index(op.f('ix_article_sentiments_company_id'), table_name='article_sentiments')
    op.drop_index(op.f('ix_article_sentiments_article_id'), table_name='article_sentiments')
    op.drop_table('article_sentiments')
    # ### end Alembic commands ###
