"""add article processing fields

Revision ID: f20b44260fb1
Revises: 11e7f525b9f2
Create Date: 2026-09-09 20:27:23.249296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20b44260fb1'
down_revision: Union[str, Sequence[str], None] = '11e7f525b9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('canonical_url', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('extracted_content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('cleaned_content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('articles', sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('articles', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_articles_extraction_status'), 'articles', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_articles_processed_at'), 'articles', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_processed_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_extraction_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_column('articles', 'processed_at')
    op.drop_column('articles', 'extraction_error')
    op.drop_column('articles', 'extraction_status')
    op.drop_column('articles', 'content_hash')
    op.drop_column('articles', 'cleaned_content')
    op.drop_column('articles', 'extracted_content')
    op.drop_column('articles', 'canonical_url')
    # ### end Alembic commands ###
